Models/Bokningar.cs
using System;

namespace HyraBilar.Models
{
    public class Bokningar
    {
        public Guid Id { get; set; }
        public Guid SkapaHyrbilarId { get; set; }
        public string SkapaHyrbilarNamn { get; set; }
        public string Bokare { get; set; }
        public DateTime Från { get; set; }
        public DateTime Till { get; set; }
    }
}

Models/DbContext.cs

using System;
using System.Collections.Generic;
using Hyrabil.Models;

namespace HyraBilar.Models
{
    public static class DbContext
    {
        public static List<SkapaHyrbilar> Hyrabilar { get; set; }
        public static List<Bokningar> Minabokningar { get; set; }

        static DbContext()
        {
            Hyrabilar = new List<SkapaHyrbilar>();

            Minabokningar = new List<Bokningar>();
            Seed();
        }

        private static void Seed()
        {
            var bil1 = new SkapaHyrbilar() { Id = Guid.NewGuid(), Namn = "Bmw", VaxelLadaType = VaxelLadaEnum.Automat, SittPlatserType = SittPlatserEnum.Fem };
            var bil2 = new SkapaHyrbilar() { Id = Guid.NewGuid(), Namn = "Tesla", VaxelLadaType = VaxelLadaEnum.Manuell, SittPlatserType = SittPlatserEnum.Sju };
            var bil3 = new SkapaHyrbilar() { Id = Guid.NewGuid(), Namn = "Ferrari", VaxelLadaType = VaxelLadaEnum.Automat, SittPlatserType = SittPlatserEnum.Två };

            Hyrabilar.Add(bil1);
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Hyrabil.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SkapaHyrbilar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Hyrabil.Models
{
    public class SkapaHyrbilar
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage ="Namn måste anges")]
        [StringLength(30, ErrorMessage = "Room name cannot be more than 30 characters.")]
        public string Namn { get; set; }


        [EnumDataType(typeof(VaxelLadaEnum))]
        public VaxelLadaEnum VaxelLadaType { get; set; }

        [EnumDataType(typeof(SittPlatserEnum))]
        public SittPlatserEnum SittPlatserType { get; set; }


        [Required(ErrorMessage = "Size is required.")]
        [Range(3, 8, ErrorMessage = "Floor must be between 0 and 100")]
        public int Sittplatser { get; set; }

    }
}
public enum VaxelLadaEnum
{
    Manuell,
    Automat
}

public enum SittPlatserEnum
{
    Två,
    Fyra,
    Fem,
    Sju
}

Models/ViewModels/CreateBokningarViewModel.cs
using Hyrabil.Models;
using System;
using System.Collections.Generic;

namespace HyraBilar.Models.ViewModels
{
    public class CreateBokningarViewModel
    {
        public static List<SkapaHyrbilar> Hyrabilar { get; set; }
        public static List<Bokningar> Minabokningar { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Hyrabil.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace HyraBilar.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HyrabilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HyraBilar.Models;
using Microsoft.AspNetCore.Mvc;

namespace HyraBilar.Controllers
{
    public class HyrabilarController : Controller
    {
        public IActionResult Index()
        {
            var Hyrabilar = DbContext.Hyrabilar;

            return View(Hyrabilar);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }
    }
}

Controllers/MinabokningarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HyraBilar.Models;
using Microsoft.AspNetCore.Mvc;

namespace HyraBilar.Controllers
{
    public class MinabokningarController : Controller
    {

        //hämta alla bilar
        public IActionResult Index()
        {
            var bookings = DbContext.Hyrabilar;
            return View(bookings);
        }
    }
}

Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home Page"; }


<h2>Välkommen Till Medas SkapaHyrbilar!</h2>
<p>Rätt pris till varje mil! </p>



<div>
    <div class="column">
        <img src="~/js/Tesla.png" alt="Tesla" style="width:100%">
        <button type="button" class="btn btn-primary btn-rounded">Hyr</button>
    </div>

    <div class="column">
        <img src="~/js/Mclaren.png" alt="Mclaren" style="width:100%">
        <button type="button" class="btn btn-danger btn-rounded">Hyr</button>
    </div>

    <div class="column">
        <img src="~/js/Lamborghini.png" alt="Lamborghini" style="width:100%">
        <button type="button" class="btn btn-success btn-rounded">Hyr</button>
    </div>

</div>

Views/Hyrabilar/Create.cshtml
@model Hyrabil.Models.SkapaHyrbilar

<h1>Skapa Hyrbil</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label class="control-label">Namn</label>
                <input class="form-control" asp-for="Namn" />
                <span asp-validation-for="Namn" class=" text-danger"></span>
            </div
            <div class="form-group">
                <label asp-for="VaxelLadaType" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="VaxelLadaType" asp-items="Html.GetEnumSelectList<VaxelLadaEnum>()">
                        <option selected="selected" value="">Please select</option>
                    </select>
                    <span asp-validation-for="VaxelLadaType" class="text-danger" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="SittPlatserType" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <select asp-for="SittPlatserType" asp-items="Html.GetEnumSelectList<SittPlatserEnum>()">
                        <option selected="selected" value="">Please select</option>
                    </select>
                    <span asp-validation-for="SittPlatserType" class="text-danger" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Sittplatser</label>
                <input class="form-control" asp-for="Sittplatser" />
                <span asp-validation-for="Sittplatser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Skapa" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Återgå</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/Hyrabilar/Index.cshtml
@model IEnumerable<Hyrabil.Models.SkapaHyrbilar>

@{ ViewData["Title"] = "Lista Av Hyrabilar"; }
<h1>@ViewData["Title"]</h1>


@{ ViewData["Title"] = "Lista av bilr"; }

<h1>Lista av bilar</h1>

<p>
    <a asp-action="Create">Skapa Ny BilHyrning</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Floor
            </th>
            <th>
                Size
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var room in Model)
        {
<tr>
    <td>@room.Namn</td>
    <td>@room.VaxelLadaType</td>
    <td>@room.SittPlatserType</td>
    <td>
        <a asp-action="Delete" asp-route-id="@room.Id">Delete</a>
        <a asp-action="Edit" asp-route-id="@room.Id">Edit</a>
    </td>
</tr>}
    </tbody>
</table>

Views/Minabokningar/Index.cshtml
@{
    ViewData["Title"] = "Mina bokningar";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HyraBilar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container" style="max-width: 120%; padding: 0;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Medas SkapaHyrbilar AB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Minabokningar" asp-action="Index">Mina Bokningar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Hyrabilar" asp-action="Index">Hyra Bilar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- <footer class="border-top footer text-muted">
        <!--
            <div class="container">
             &copy; 2020 - HyraBilar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
         </div>

    </footer>
        </-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>